basePath: /api/v1
definitions:
  errors.Code:
    enum:
    - UNKNOWN_ERROR
    - INTERNAL_SERVER_ERROR
    - BAD_REQUEST
    - UNAUTHORIZED
    - FORBIDDEN
    - NOT_FOUND
    - USER_NOT_FOUND
    - SESSION_NOT_FOUND
    - INVALID_PASSWORD
    - WALLET_NOT_FOUND
    - INVALID_STATUS_TRANSITION
    - DUPLICATE_REFERENCE
    - TRANSACTION_NOT_FOUND
    - INSUFFICIENT_BALANCE
    type: string
    x-enum-varnames:
    - ErrCodeUnknownError
    - ErrCodeInternalServerError
    - ErrCodeBadRequest
    - ErrCodeUnauthorized
    - ErrCodeForbidden
    - ErrCodeNotFound
    - ErrCodeUserNotFound
    - ErrCodeSessionNotFound
    - ErrCodeInvalidPassword
    - ErrCodeWalletNotFound
    - ErrCodeInvalidStatusTransition
    - ErrCodeDuplicateReference
    - ErrCodeTransactionNotFound
    - ErrCodeInsufficientBalance
  ewallet-wallet_internal_dto_transaction_dto.TransactionPaginationResponse:
    properties:
      amount:
        type: number
      created_at:
        type: string
      transaction_type:
        type: string
    type: object
  ewallet-wallet_internal_dto_transaction_dto.TransactionRequest:
    properties:
      amount:
        example: 10000
        type: number
    required:
    - amount
    type: object
  ewallet-wallet_internal_dto_transaction_dto.TransactionResponse:
    properties:
      balance:
        type: number
    type: object
  ewallet-wallet_internal_dto_wallet_dto.CreateWalletRequest:
    properties:
      user_id:
        type: integer
    required:
    - user_id
    type: object
  ewallet-wallet_internal_dto_wallet_dto.CreateWalletResponse:
    properties:
      balance:
        type: number
      id:
        type: integer
      user_id:
        type: integer
    type: object
  ewallet-wallet_internal_dto_wallet_dto.GetBalanceResponse:
    properties:
      balance:
        type: number
    type: object
  response.BadRequestResponse:
    properties:
      error_code:
        $ref: '#/definitions/errors.Code'
      errors:
        items:
          $ref: '#/definitions/response.ValidationErrorField'
        type: array
      message:
        type: string
    type: object
  response.ErrorResponse:
    properties:
      error_code:
        $ref: '#/definitions/errors.Code'
      message:
        type: string
    type: object
  response.SuccessResponse:
    properties:
      data: {}
      message:
        type: string
      meta: {}
    type: object
  response.ValidationErrorField:
    properties:
      field:
        type: string
      message:
        type: string
    type: object
host: localhost:8081
info:
  contact: {}
  description: |-
    API Service for wallet user.
    <br/><b>Developer:</b> Muhammad Brilian Satria Utama
    <b>Environment:</b> Development
  title: E Wallet API (Wallet Service)
  version: "0.0"
paths:
  /wallet-transaction/credit:
    put:
      consumes:
      - application/json
      description: Adds funds to the user's wallet.
      parameters:
      - description: Bearer <token>
        in: header
        name: Authorization
        required: true
        type: string
      - description: Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/ewallet-wallet_internal_dto_transaction_dto.TransactionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/response.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/ewallet-wallet_internal_dto_transaction_dto.TransactionResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.BadRequestResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Credit Wallet
      tags:
      - Transaction
  /wallet-transaction/debit:
    put:
      consumes:
      - application/json
      description: Deducts funds from the user's wallet.
      parameters:
      - description: Bearer <token>
        in: header
        name: Authorization
        required: true
        type: string
      - description: Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/ewallet-wallet_internal_dto_transaction_dto.TransactionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/response.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/ewallet-wallet_internal_dto_transaction_dto.TransactionResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.BadRequestResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Debit Wallet
      tags:
      - Transaction
  /wallet-transaction/history:
    get:
      consumes:
      - application/json
      description: Deducts funds from the user's wallet.
      parameters:
      - description: Bearer <token>
        in: header
        name: Authorization
        required: true
        type: string
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 10
        description: Number of items per page
        in: query
        name: size
        type: integer
      - description: Filter by type (CREDIT/DEBIT)
        in: query
        name: transactionType
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/response.SuccessResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/ewallet-wallet_internal_dto_transaction_dto.TransactionPaginationResponse'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.BadRequestResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - BearerAuth: []
      summary: History User's Transaction
      tags:
      - Transaction
  /wallet/:
    post:
      consumes:
      - application/json
      description: Registers a new wallet for the user.
      parameters:
      - description: Bearer <token>
        in: header
        name: Authorization
        required: true
        type: string
      - description: Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/ewallet-wallet_internal_dto_wallet_dto.CreateWalletRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            allOf:
            - $ref: '#/definitions/response.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/ewallet-wallet_internal_dto_wallet_dto.CreateWalletResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.BadRequestResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Create User's Wallet
      tags:
      - Wallet
  /wallet/balance:
    get:
      consumes:
      - application/json
      description: Retrieves the current balance of the user's wallet.
      parameters:
      - description: Bearer <token>
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/response.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/ewallet-wallet_internal_dto_wallet_dto.GetBalanceResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.BadRequestResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Get Balance of the User's Wallet
      tags:
      - Wallet
swagger: "2.0"
